apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: manila-cephfs-share-ond
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: manila-provisioner
parameters:
  type: cephfsnativetype
  zones: nova
  osSecretName: manila-secrets
  osSecretNamespace: default
  protocol: CEPHFS
  backend: cephfs
